### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by idrp** [DonHulieo/don-jewelery#1]
I have had people camping in the Jewellery shop to avoid having to thermite the doors, is there a way that they have to thermite in order to be able to smash the vitrines?

**Comment by DonHulieo** [comment]
Yea mate, this seems like an issue for sure. I haven't ran this myself on a live server yet, so haven't encountered that issue.
I'll look into adding a check for thermite or hack. 

As a way to help stop this immediately, I would change the item the Vangelico's PC hack requires to something hard for your players to acquire, and when they camp the store they'll be stuck until daytime and the police can arrest and charge them.

**Comment by DonHulieo** [comment]
Added a check then, script is updated and fixed! Thanks for bringing this up, closing this issue.
