### ISSUE TITLE
grape seed

### ISSUE THREAD

**Issue by Sully1796376** [DonHulieo/don-jewelery#3]
in grape seed there is a couple of cases missing and also ps dispatch not working any help please buddy

**Comment by DonHulieo** [comment]
Not all the cases in the GigZ Jewel stores cases are breakable, and that relates to the props used for the cases, it doesn't make sense for only some of them to smash, so I've intentionally not setup those cases to be 'hit'.

If ps-dispatch is non-functional, you've more than likely not added the CameraIDs to the qb-policejob config.lua.

**Comment by DonHulieo** [comment]
![image](https://user-images.githubusercontent.com/96005229/212538006-ede6cc32-d830-4ac7-9966-6ba6a0373770.png)
