### ISSUE TITLE
no blips?

### ISSUE THREAD

**Issue by Andyauk** [DonHulieo/don-jewelery#4]
So unless you F8 ensure or restart the script the blips don't show anymore.

**Comment by DonHulieo** [comment]
This isn't an issue for me, has this happened after installing the latest version or has the happened to an existing copy of the script?

**Comment by Andyauk** [comment]
> This isn't an issue for me, has this happened after installing the latest version or has the happened to an existing copy of the script?

latest version. fresh install, on both server and this script to test.

**Comment by DonHulieo** [comment]
Are there any other issues, or does it all work fine? Also, to clarify, are you using one or three stores?

**Comment by Andyauk** [comment]
> Are there any other issues, or does it all work fine? Also, to clarify, are you using one or three stores?

No issues, no F8, I've done 2 out of the 3 locations no issues. Seems to be just the blips.

**Comment by DonHulieo** [comment]
Alright, I'll try and see if I can repeat it, otherwise if you find a fix, pr it :)

**Comment by Andyauk** [comment]
> Alright, I'll try and see if I can repeat it, otherwise if you find a fix, pr it :)

That's why I messaged here, as I can't find it, as I was going to try fix it . I think it's based off (resource start)

**Comment by DonHulieo** [comment]
I think I found your issue, try commenting out line 489 and 491 (separately) in the client/main.lua and report back how it goes.

`  -- if not DoesBlipExist(blip) then`
`    createBlips()`
 ` -- end`

**Comment by Andyauk** [comment]
> I think I found your issue, try commenting out line 489 and 491 (separately) in the client/main.lua and report back how it goes.
> 
> ` -- if not DoesBlipExist(blip) then` ` createBlips()` ` -- end`

worked great. they show up again.

**Comment by DonHulieo** [comment]
> > I think I found your issue, try commenting out line 489 and 491 (separately) in the client/main.lua and report back how it goes.
> > ` -- if not DoesBlipExist(blip) then` ` createBlips()` ` -- end`
> 
> worked great. they show up again.

Just means you have another script that uses the same blip and mine gets confused, glad it's fixed!

**Comment by Andyauk** [comment]
> > > I think I found your issue, try commenting out line 489 and 491 (separately) in the client/main.lua and report back how it goes.
> > > ` -- if not DoesBlipExist(blip) then` ` createBlips()` ` -- end`
> > 
> > 
> > worked great. they show up again.
> 
> Just means you have another script that uses the same blip and mine gets confused, glad it's fixed!

as in blip icon? as i can find that if the case

**Comment by DonHulieo** [comment]
> > > > I think I found your issue, try commenting out line 489 and 491 (separately) in the client/main.lua and report back how it goes.
> > > > ` -- if not DoesBlipExist(blip) then` ` createBlips()` ` -- end`
> > > 
> > > 
> > > worked great. they show up again.
> > 
> > 
> > Just means you have another script that uses the same blip and mine gets confused, glad it's fixed!
> 
> as in blip icon? as i can find that if the case

Yea mate, 617 is the sprite number

**Comment by Andyauk** [comment]
> > > > > I think I found your issue, try commenting out line 489 and 491 (separately) in the client/main.lua and report back how it goes.
> > > > > ` -- if not DoesBlipExist(blip) then` ` createBlips()` ` -- end`
> > > > 
> > > > 
> > > > worked great. they show up again.
> > > 
> > > 
> > > Just means you have another script that uses the same blip and mine gets confused, glad it's fixed!
> > 
> > 
> > as in blip icon? as i can find that if the case
> 
> Yea mate, 617 is the sprite number

thanks for your time and help.
